schema_version = "1.0.0"

id = "sculpt_layers_multires"
version = "1.13.24"
name = "Sculpt Layers for Multires"
tagline = "Per-mesh multi-layer Multires sculpting with strength control"
maintainer = "beni"
type = "add-on"

# Source + support (Issues): https://github.com/beni-bd/sculpt-layers-multires/issues
website = "https://github.com/beni-bd/sculpt-layers-multires"

tags = ["Sculpt"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024-2026 beni",
]
